[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-login>=0.6.3",
    "flask>=3.1.2",
    "requests>=2.32.5",
    "oauthlib>=3.3.1",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=21.2.0",
]
